config/routes.rb
Bloge::Application.routes.draw do
  resources :setup, only: [:index, :create]

  devise_for :users
  namespace :admin do 
    resources :posts
    root to: 'home#index'
  end
  resources :posts, only: [:index, :show]

  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  before_filter :authenticate_user!
  
  def index
    
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_filter :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: admin_post_path(@post) }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :published_at)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_setup

  def index
    @posts = Post.limit(10).order('published_at desc')
  end

  def show
    @post = Post.find(params[:id])

  end

  private
    def check_setup
      unless User.any?
        redirect_to setup_index_path
        return false
      end
    end
end

app/controllers/setup_controller.rb
class SetupController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :check_users

  def index
  end


  def create

    # Set up the first user
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_to admin_posts_path
    else
      flash[:alert] = 'There was an error setting up this site. Please try again.'
      render :index
    end
  end


  private
    def check_users
      if User.any?
        redirect_to root_path
        return false
      end
    end


    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def text_to_html (text)
    Moredown.text_to_html(text).html_safe
  end
end

app/views/admin/home/index.html.haml
.panel 
  Nothing to see here... yet.

app/views/admin/posts/_form.html.haml
= form_for [:admin, @post] do |f|
  - if @post.errors.any?
    #error_explanation
      %h2 
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:

      %ul
        - @post.errors.full_messages.each do |msg|
          %li
            = msg
  .field
    = f.label :title
    = f.text_field :title            

  .field
    = f.label :body
    = f.text_area :body 

  .field
    = f.label :published_at
    = f.datetime_select :published_at 

  .actions
    = f.submit 'Submit', :class => "button create"

app/views/admin/posts/edit.html.haml
.panel
  .gutter-left
    = link_to admin_posts_path do
      .icon-back.back-icon
  .gutter-left-panel
    %h1 Editting Post

    = render 'form'

  

app/views/admin/posts/index.html.haml
.panel
  %h2
    Blog Posts | 
  = link_to '+ New Post', new_admin_post_path, :class => 'posts button'
  - @posts.each do |post|
    .post
      = link_to post do
        %h1
          = post.title
      %span.pubish_at
        = post.published_at
      %p 
        = post.body

      = link_to 'Edit', edit_admin_post_path(post), :class => 'edit button' 
      = link_to 'Remove', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'remove button' 

app/views/admin/posts/new.html.haml
.panel
  .gutter-left
    = link_to admin_posts_path do
      .icon-back.back-icon
  .gutter-left-panel

    %h1 New Post

    = render 'form'
  

app/views/admin/posts/show.html.haml
.panel
  %p{:id => "notice"}
    = notice

  %p
    %strong Title:
    = @post.title

  %p
    %strong Body:
    = @post.body

  %p
    %strong Published at:
    = @post.published_at

  = link_to 'Edit', edit_admin_post_path(@post) |
  = link_to 'Back', admin_posts_path

app/views/layouts/admin.html.haml
!!! XHTML 5
%html{html_attrs}
  %head
    %title
      Bloge
        
    %link{ rel: 'icon', type: 'image/png', href: asset_path('.png') }/
    %meta{ name: "keywords", content: "" }/
    %meta{ name: "viewport", content: "width=device-width, minimum-scale=1.0, maximum-scale=1.0" }/
    = stylesheet_link_tag "admin", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    .background
    .nav
      %ul
        = link_to admin_root_path do
          %li.dashboard
            .icon-dashboard
            Dashboard

        = link_to admin_posts_path do
          %li.posts
            .icon-posts
            Posts

        = link_to admin_posts_path do
          %li.assets
            .icon-assets
            Assets

        = link_to admin_posts_path do
          %li.settings
            .icon-gear
            Settings

    .panel
      %h1
        Bloge
      .user-panel
        .user-email
          = current_user.email
        .user-logout
          = link_to destroy_user_session_path, method: :delete do
            Sign Out

    = yield

app/views/layouts/application.html.haml
!!! XHTML 5
%html{html_attrs}
  %head
    %title
      Yes, I registered this URL and bought a private server just to spite you. 
        
    %link{ rel: 'icon', type: 'image/png', href: asset_path('.png') }/
    %meta{ name: "keywords", content: "" }/
    %meta{ name: "viewport", content: "width=device-width, minimum-scale=1.0, maximum-scale=1.0" }/
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    / .nav
    /   %h1
    /     Much Bloge. Wow
    
    = yield
   

app/views/posts/index.haml
You Chelsea, are a bitch. 
%br
Your move, love Jack.

app/views/posts/show.haml
.post
  %h1 
    = @post.title
  %p 
    = text_to_html(@post.body)

app/views/setup/index.html.haml
.modal-content
  = form_tag '/setup', method: :post, class: 'form-horizontal' do
    .modal-header
      %h2 Looks like this is a brand new site
      %p Let's get you set up

    .modal-body
      - if @user
        = render 'layouts/notices', errors: @user.errors

      .form-group
        = label_tag 'user[email]', 'Email', class: 'col-sm-4 control-label'
        .col-sm-8
          = text_field_tag 'user[email]', '', class: 'form-control'
          .help-block You will sign in with this email

      .form-group
        = label_tag 'user[password]', 'Password', class: 'col-sm-4 control-label'
        .col-sm-8
          = password_field_tag 'user[password]', '', class: 'form-control'

      .form-group
        = label_tag 'user[password_confirmation]', 'Confirm password', class: 'col-sm-4 control-label'
        .col-sm-8
          = password_field_tag 'user[password_confirmation]', '', class: 'form-control'


    .modal-footer
      = submit_tag 'Save this and take me to my site', class: 'btn btn-primary'